name: Kitin CI

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '25'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Configure Git
        run: |
          git config --global user.email "ci@kitinmc.com"
          git config --global user.name "Kitin CI"

      - name: Apply Patches
        run: ./gradlew applyAllPatches

      - name: Create Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar

      - name: Extract Metadata
        id: meta
        run: |
          echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "build_date=$(date -u +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
          JAR_PATH=$(find kitin-server/build/libs/ -name "*-paperclip-*-mojmap.jar" | head -n 1)
          echo "jar_path=$JAR_PATH" >> $GITHUB_ENV
          echo "jar_name=$(basename $JAR_PATH)" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kitin-Build-JAR
          path: ${{ env.jar_path }}

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: build-${{ env.commit_id }}
          name: Kitin Core - ${{ env.commit_id }}
          body: |
            ### 🚀 Kitin Core
            - **Build Date**: `${{ env.build_date }}`
            - **Commit**: [${{ env.commit_id }}](https://github.com/${{ github.repository }}/commit/${{ env.commit_id }})
            
            #### 📦 Download
            
            > Automatically built by GitHub Actions.
          artifacts: ${{ env.jar_path }}
          allowUpdates: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}