name: Kitin CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '25'

      - name: Config Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew

      - name: Apply Patches
        run: |
          ./gradlew applyAllPatches

      - name: CreateJar
        run: |
          ./gradlew createMojmapPaperclipJar

      - name: Push to API
        continue-on-error: true
        run: |
          ./gradlew --refresh-dependencies generateDevelopmentBundle publish -PpublishDevBundle=true
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.project_id_b }} CI Artifacts
          path: kitin-server/build/libs/*-paperclip-*-mojmap.jar

      - name : SetENV
        run: |
          sh scripts/SetENV.sh

      - name: Get build info
        id: build-info
        run: |
          BUILD_DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
          echo "build_date=$BUILD_DATE" >> $GITHUB_ENV

      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.tag }}
          name: ${{ env.project_id_b }} ${{ env.mcversion }} - ${{ env.commit_id }}
          body: |
            ### 📦 Version: `${{ env.mcversion }}` | Commit: [${{ env.commit_id }}](https://github.com/${{ github.repository }}/commit/${{ env.commit_id }})
            [![download](https://img.shields.io/github/downloads/SucIXR/${{ env.project_id }}/${{ env.tag }}/total?color=red&style=flat-square)](https://github.com/MenthaMC/${{ env.project_id }}/releases/download/${{ env.tag }}/${{ env.jar }})

            > This release is automatically built by GitHub Actions.

            #### 📜 Changes since last release:
            ${{ env.commit_msg }}

            #### 📊 Build Information:
            - **Build Status**: ✅ Success
            - **Build Date**: ${{ env.build_date }}
          artifacts: ${{ env.jar_dir }}
          generateReleaseNotes: true
          prerelease: ${{ env.pre }}
          makeLatest: ${{ env.make_latest }}
          token: ${{ secrets.GITHUB_TOKEN }}