name: Kitin CI

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'corrett'
          java-version: '25'

      - name: Configure Git
        run: |
          git config --global user.email "ci@kitinmc.com"
          git config --global user.name "Kitin CI"

      - name: Apply Patches
        run: ./gradlew applyAllPatches

      - name: Build Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar

      - name: Set Environment Variables
        run: sh scripts/SetENV.sh

      - name: Get Build Date
        run: echo "build_date=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kitin-CI-Artifacts
          path: kitin-server/build/libs/*-paperclip-*-mojmap.jar

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.tag }}
          name: Kitin ${{ env.mcversion }} - ${{ env.commit_id }}
          body: |
            ### 📦 Kitin Core Build
            - **Minecraft Version**: `${{ env.mcversion }}`
            - **Commit**: [${{ env.commit_id }}](https://github.com/${{ github.repository }}/commit/${{ env.commit_id }})
            - **Build Date**: ${{ env.build_date }}
            
            > This release is automatically built by GitHub Actions.
            
            #### 📜 Latest Commit Message:
            ${{ github.event.head_commit.message }}
          artifacts: kitin-server/build/libs/*-paperclip-*-mojmap.jar
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}